---
title: "Scenario_test(5) SCAD MCP lambda by cross-validation"
output: pdf_document
---

```{r,echo=FALSE}
load("Scenario_beta_3_1.5.Rdata")
```

```{r,echo=FALSE}
print(paste("beta : ",paste(table_res1$beta_estimation_all$beta,collapse = " ")))
print(paste("sample size is: ",as.character(table_res1$beta_estimation_all$sample_size)))
table_list <- table_res1$result_list
for(i in 1:length(table_list)){
  print(names(table_list)[i])
  print(round(table_list[[i]],3))
}
```

Difference between estimation and true beta value

```{r,echo=FALSE}
diff_list <- table_res1$beta_diff
for(i in 1:length(diff_list)){
  print(names(diff_list)[i])
  print(round(diff_list[[i]],3))
  print("the mean bias is:")
  print(round(colMeans(diff_list[[i]]),3))
}
```

\pagebreak

beta: c(1.5,2,3,rep(0,5))

n: 30

```{r,echo=FALSE}
load("Scenario_beta_1.5_2.Rdata")
```

```{r,echo=FALSE}
table_list <- table_res1$result_list
for(i in 1:length(table_list)){
  print(names(table_list)[i])
  print(round(table_list[[i]],3))
}
```

Difference between estimation and true beta value

```{r,echo=FALSE}
diff_list <- table_res1$beta_diff
for(i in 1:length(diff_list)){
  print(names(diff_list)[i])
  print(round(diff_list[[i]],3))
  print("the mean bias is:")
  print(round(colMeans(diff_list[[i]]),3))
}
```

\pagebreak

beta: c(3,1.5,rep(0,2),2,rep(0,3)) loss.9999

n: 30

```{r,echo=FALSE}
load("Scenario_beta_3_1.5_.9999.Rdata")
```

```{r,echo=FALSE}
table_list <- table_res1$result_list
for(i in 1:length(table_list)){
  print(names(table_list)[i])
  print(round(table_list[[i]],3))
}
```

Difference between estimation and true beta value

```{r,echo=FALSE}
diff_list <- table_res1$beta_diff
for(i in 1:length(diff_list)){
  print(names(diff_list)[i])
  print(round(diff_list[[i]],3))
  print("the mean bias is:")
  print(round(colMeans(diff_list[[i]]),3))
}
```

\pagebreak

beta: c(1.5,2,3,rep(0,5)) loss_rate=1

n: 100

```{r,echo=FALSE}
load("Scenario_beta_1.5_2_0.9999.Rdata")
```

```{r,echo=FALSE}
table_list <- table_res1$result_list
for(i in 1:length(table_list)){
  print(names(table_list)[i])
  print(round(table_list[[i]],3))
}
```

Difference between estimation and true beta value

```{r,echo=FALSE}
diff_list <- table_res1$beta_diff
for(i in 1:length(diff_list)){
  print(names(diff_list)[i])
  print(round(diff_list[[i]],3))
  print("the mean bias is:")
  print(round(colMeans(diff_list[[i]]),3))
}
```

\pagebreak
